services:
  cell:
    image: conwaycellsqak:1.0
    environment:
      - MQTTBROKER_URL=tcp://mosquitto:1883
    deploy:
      replicas: 9
    ports:
      - "8361-8369:8360"
    networks:
      - cargo-network

networks:
  cargo-network:
    driver: overlay
    
# docker swarm init    
# docker stack deploy -c docker-compose-swarm.yml mystack
# docker stack ls    
# docker stack rm mystack
# docker swarm leave --force


# docker network create --driver overlay cargo-network