/* Generated by AN DISI Unibo */ 
package it.unibo.gridcreator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Gridcreator ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 
		 	var RowsN = 0; var ColsN=0; var CellSize=0 
		 	val neighBornFName = "cellnbs.pl"
		 	val cellsFName     = "grid.pl"	
		    var NAllCells      =  0  //set in s0
		    var NCellsCreated  =  0  //set in handlecellecreated 		
		    var NCellended      = 0  //set in terminatethegame
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 
								val res =
							conway.GridSupport.readGridConfig("gridConfig.json")
								      RowsN     = res.get(0)
								      ColsN     = res.get(1)
								      NAllCells = RowsN * ColsN       
						CommUtils.outblue("$name | NAllCells=$NAllCells")
						delay(1000) 
						
							  conway.GridSupport.createCellsLocal(
									myself,RowsN,ColsN,neighBornFName,cellsFName)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handlecellcreated",cond=whenDispatch("cellcreated"))
				}	 
				state("handlecellcreated") { //this:State
					action { //it:State
						 NCellsCreated = NCellsCreated + 1  
						if(  NCellsCreated == NAllCells  
						 ){CommUtils.outblack("$name | ACTORS in ${context!!.name} ${sysUtil.getAllActorNames()}")
						forward("gameready", "gameready($NAllCells)" ,"gamelife" ) 
						forward("gameready", "gameready($NAllCells)" ,"griddisplay" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="handlecellcreated",cond=whenDispatch("cellcreated"))
					transition(edgeName="t02",targetState="terminatethegame",cond=whenDispatch("cellends"))
				}	 
				state("terminatethegame") { //this:State
					action { //it:State
						 NCellended = NCellended + 1  
						if(  NCellended == NAllCells  
						 ){forward("gameended", "gameended($NAllCells)" ,"gamelife" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="terminatethegame",cond=whenDispatch("cellends"))
				}	 
			}
		}
} 
