/* Generated by AN DISI Unibo */ 
package it.unibo.exec_getall

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.domain.*

class Exec_getall ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		val psl = ProductServiceLogic.getSingleton()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | STARTS")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="handle_getAll",cond=whenRequest("getAllProducts"))
				}	 
				state("handle_getAll") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 var ASNWR = "unknown"  
						if( checkMsgContent( Term.createTerm("dummy(ID)"), Term.createTerm("dummy(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  
											   val ALLPRODS = psl.getAllProducts()           //return List<String>
											   if( ALLPRODS != null  ) ASNWR = ALLPRODS.toString() //"'"+ALLPRODS.toString()+"'"
											   else ASNWR = "empty"
								CommUtils.outgreen("$name | handle_getAll ALLPRODS=$ALLPRODS  ")
								answer("getAllProducts", "getAllProductsAnswer", "products($ASNWR)"   )  
						}
						CommUtils.outgreen("$name | ENDS")
						//terminate(0)
						context!!.removeInternalActor(myself)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
