##version: '2.1'
services:
  master:
    image: conwaymasterqak:1.0
    environment:
      - MQTTBROKER_URL=tcp://mosquitto:1883
      - CELLS=3
    ports:
      - "8260:8260"
#    restart: always
    networks:
      - cargo-network

 


networks:
   cargo-network:
     external: true
    
 ## docker-compose -f docker-compose-master.yml -p conwaymaster up   