
services:
  bwbscrbt:
    container_name: bwbscrbt
    image: bwbscrbt:1.0
    ports:
      - 8720:8720/tcp
      - 8720:8720/udp
    networks:
      - iss-network
 
  
 
networks:
  iss-network:
    external: true
 
### docker-compose -f bwbscrbt.yaml  up
 