/* Generated by AN DISI Unibo */ 
package it.unibo.cell_1_1

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.*

class Cell_1_1 ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
			   var MyState     = false
			   var Countnb     = 0  //numero dei vicini
			   var Countnbon   = 0  //numero degli stati on dei vicini
			   var Countnbmsgs = 0  //numero dei msg ricevuti dai vicini	  
			   var  X          = 1  //SET A-PRIORI
			   var  Y          = 1  //SET A-PRIORI
		 	   var XD          = 2  //SET A-PRIORI
		 	   var YD          = 2  //SET A-PRIORI
			   
			   lateinit  var outindev  : OutInCellOnRasp
			   val guiinterpreter = main.java.CellCmdTranslator( myself )  //ADDED
		 		 
		   
		  
		  fun displayOnGui(){ 
			val V   = if (MyState) 1 else 0
			val msg = "cell($XD,$YD,$V)" 
			outindev.display(msg)   	    
		  }
		  
		  fun diplayLed( V : Boolean){
		  	if( V ) Runtime.getRuntime().exec("python ledPython25On.py"); 
		  	else Runtime.getRuntime().exec("python ledPython25Off.py");
		  }
		
		  fun displayLedState(){
		  	displayOnGui();
		  	diplayLed( MyState );
		  }
		  
		  CommUtils.outyellow("STARTSSSSSSSSSSSSSS")
		        
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | START X=$X Y=$Y ")
						delay(3000) 
						CommUtils.outblue("$name | STARTSSSSSSSSSSSSSS")
						  //setCellCoords( )
									Countnb = conway.GridSupport25.subscribeToNeighborsMqtt(myself, X,Y)
						CommUtils.outgreen("$name | STARTS Countnb= $Countnb")
						 outindev = OutInCellOnRasp(myself, "guiin")  
						 diplayLed( true )  
						delay(2000) 
						 diplayLed( false )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="clearThecell",cond=whenEvent("clearCell"))
					transition(edgeName="t01",targetState="changeCellState",cond=whenDispatch("changeCellState"))
					transition(edgeName="t02",targetState="emitinfophase",cond=whenEvent("startthegame"))
					interrupthandle(edgeName="t03",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
				state("handleGuiMsg") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("kernel_rawmsg(ARG)"), Term.createTerm("kernel_rawmsg(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 guiinterpreter.cvtToApplMessage( payloadArg(0) )  
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("changeCellState") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("changeCellState(X,Y)"), Term.createTerm("changeCellState(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  X == payloadArg(0).toInt() && Y == payloadArg(1).toInt()  
								 ){  MyState = ! MyState;
													displayLedState()
								CommUtils.outyellow("$name | STATE=$MyState ")
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="clearThecell",cond=whenEvent("clearCell"))
					transition(edgeName="t05",targetState="changeCellState",cond=whenDispatch("changeCellState"))
					transition(edgeName="t06",targetState="emitinfophase",cond=whenEvent("startthegame"))
					interrupthandle(edgeName="t07",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
				state("emitinfophase") { //this:State
					action { //it:State
						 var MyInfo = "$name,$MyState"  
						CommUtils.outgreen("$name | emitinfophase")
						 emitstreammqtt(name, "curstate","curstate($MyInfo)")  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="stopthecell",cond=whenEvent("stopthecell"))
					transition(edgeName="t09",targetState="elabinfophase",cond=whenEvent("curstate"))
					interrupthandle(edgeName="t010",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
				state("elabinfophase") { //this:State
					action { //it:State
						 Countnbmsgs=Countnbmsgs+1  
						CommUtils.outgreen("$name | elabinfophase $Countnbmsgs")
						if( checkMsgContent( Term.createTerm("curstate(NB,STATE)"), Term.createTerm("curstate(NB,true)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Countnbon = Countnbon + 1   
						}
						if(  Countnbmsgs == Countnb  
						 ){forward("allnbreceived", "allnbreceived(ok)" ,name ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="stopthecell",cond=whenEvent("stopthecell"))
					transition(edgeName="t012",targetState="elabinfophase",cond=whenEvent("curstate"))
					transition(edgeName="t013",targetState="elabstatephase",cond=whenDispatch("allnbreceived"))
					interrupthandle(edgeName="t014",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
				state("elabstatephase") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | elabstatephase $MyState $Countnbon")
						if(  MyState   
						 ){ MyState = Countnbon==2 || Countnbon==3  
						}
						else
						 {if(  ! MyState   
						  ){ MyState = (Countnbon==3)  
						 }
						 }
						 Countnbmsgs = 0
								   Countnbon   = 0 
						           displayLedState() 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_elabstatephase", 
				 	 					  scope, context!!, "local_tout_"+name+"_elabstatephase", 1000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t015",targetState="emitinfophase",cond=whenTimeout("local_tout_"+name+"_elabstatephase"))   
					transition(edgeName="t016",targetState="stopthecell",cond=whenEvent("stopthecell"))
					transition(edgeName="t017",targetState="clearThecell",cond=whenEvent("clearCell"))
					transition(edgeName="t018",targetState="changeCellState",cond=whenDispatch("changeCellState"))
					interrupthandle(edgeName="t019",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
				state("stopthecell") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | stopthecell ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t020",targetState="changeCellState",cond=whenDispatch("changeCellState"))
					transition(edgeName="t021",targetState="emitinfophase",cond=whenEvent("startthegame"))
					transition(edgeName="t022",targetState="clearThecell",cond=whenEvent("clearCell"))
					interrupthandle(edgeName="t023",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
				state("clearThecell") { //this:State
					action { //it:State
						 MyState = false  
						 displayLedState()  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="changeCellState",cond=whenDispatch("changeCellState"))
					transition(edgeName="t025",targetState="emitinfophase",cond=whenEvent("startthegame"))
					transition(edgeName="t026",targetState="clearThecell",cond=whenEvent("clearCell"))
					transition(edgeName="t027",targetState="stopthecell",cond=whenEvent("stopthecell"))
					interrupthandle(edgeName="t028",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
			}
		}
} 
