/* Generated by AN DISI Unibo */ 
package it.unibo.cell

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.*

class Cell ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
			   var MyState     = false
			   var Countnb     = 0  //numero dei vicini
			   var Countnbon   = 0  //numero degli stati on dei vicini
			   var Countnbmsgs = 0  //numero dei msg ricevuti dai vicini	  
			   var  X          = 0
			   var  Y          = 0
			   var XD          = 0
			   var YD          = 0
			   
			   lateinit  var outindev  : OutInCellGui
			   val guiinterpreter = main.java.CellCmdTranslator( myself )  //ADDED
		 		 
		 fun setCellCoords( )  {
		     val coords = name.replace("cell_","").split("_")  //Before cellc
		     X = coords[0].toInt()
		     XD = X+1
		     Y  = coords[1].toInt()        
		     YD =Y+1
		  }
		  
		  fun displayOnGui(){ 
			val V   = if (MyState) 1 else 0
			val msg = "cell($XD,$YD,$V)" 
			outindev.display(msg)   	
		  }
		        
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(3000) 
						 setCellCoords( )
									Countnb = conway.GridSupport25.subscribeToNeighborsMqtt(myself, X,Y)
						CommUtils.outblack("$name | STARTS Countnb= $Countnb")
						 outindev = OutInCellGui(myself, "guiin")  
						
						  		   val cmd   = CommUtils.buildDispatch(
						 		   		name,"cellcreated","cellcreated( $MyName,false )","gamebuilder" )
						 		   publish( cmd.toString(), "unibo/qak/gamebuilder" )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t029",targetState="clearThecell",cond=whenEvent("clearCell"))
					transition(edgeName="t030",targetState="changeCellState",cond=whenDispatch("changeCellState"))
					transition(edgeName="t031",targetState="emitinfophase",cond=whenEvent("startthegame"))
					interrupthandle(edgeName="t032",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
				state("changeCellState") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("changeCellState(X,Y)"), Term.createTerm("changeCellState(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  X == payloadArg(0).toInt() && Y == payloadArg(1).toInt()  
								 ){  MyState = ! MyState;
													displayOnGui()
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t033",targetState="clearThecell",cond=whenEvent("clearCell"))
					transition(edgeName="t034",targetState="changeCellState",cond=whenDispatch("changeCellState"))
					transition(edgeName="t035",targetState="emitinfophase",cond=whenEvent("startthegame"))
					interrupthandle(edgeName="t036",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
				state("handleGuiMsg") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("kernel_rawmsg(ARG)"), Term.createTerm("kernel_rawmsg(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 guiinterpreter.cvtToApplMessage( payloadArg(0) )  
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t037",targetState="emitinfophase",cond=whenEvent("startthegame"))
					transition(edgeName="t038",targetState="changeCellState",cond=whenDispatch("changeCellState"))
					transition(edgeName="t039",targetState="clearThecell",cond=whenEvent("clearCell"))
					interrupthandle(edgeName="t040",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
				state("emitinfophase") { //this:State
					action { //it:State
						 var MyInfo = "$name,$MyState"  
						 emitstreammqtt(name, "curstate","curstate($MyInfo)")  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t041",targetState="elabinfophase",cond=whenEvent("curstate"))
				}	 
				state("elabinfophase") { //this:State
					action { //it:State
						 Countnbmsgs=Countnbmsgs+1  
						if( checkMsgContent( Term.createTerm("curstate(NB,STATE)"), Term.createTerm("curstate(NB,true)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Countnbon = Countnbon + 1   
						}
						if(  Countnbmsgs == Countnb  
						 ){forward("allnbreceived", "allnbreceived(ok)" ,name ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t042",targetState="elabinfophase",cond=whenEvent("curstate"))
					transition(edgeName="t043",targetState="elabstatephase",cond=whenDispatch("allnbreceived"))
				}	 
				state("elabstatephase") { //this:State
					action { //it:State
						if(  MyState   
						 ){ MyState = Countnbon==2 || Countnbon==3  
						}
						if(  ! MyState   
						 ){ MyState = (Countnbon==3)  
						}
						 Countnbmsgs = 0
								   Countnbon   = 0 
						           displayOnGui() 
						
						   		   val cmd   = CommUtils.buildDispatch(
						   		   	 name,"cellready","cellready($MyName,$MyState)","gamemaster")
						   		   publish( cmd.toString(), "unibo/qak/gamemaster" )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t044",targetState="emitinfophase",cond=whenEvent("synch"))
					transition(edgeName="t045",targetState="stopthecell",cond=whenEvent("stopthecell"))
				}	 
				state("stopthecell") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t046",targetState="changeCellState",cond=whenDispatch("changeCellState"))
					transition(edgeName="t047",targetState="emitinfophase",cond=whenEvent("startthegame"))
					transition(edgeName="t048",targetState="clearThecell",cond=whenEvent("clearCell"))
					interrupthandle(edgeName="t049",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
				state("clearThecell") { //this:State
					action { //it:State
						 MyState = false  
						 displayOnGui()  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t050",targetState="changeCellState",cond=whenDispatch("changeCellState"))
					transition(edgeName="t051",targetState="emitinfophase",cond=whenEvent("startthegame"))
					transition(edgeName="t052",targetState="clearThecell",cond=whenEvent("clearCell"))
					interrupthandle(edgeName="t053",targetState="handleGuiMsg",cond=whenEvent("kernel_rawmsg"),interruptedStateTransitions)
				}	 
			}
		}
} 
